[package]
name = "feather_calendar"
version = "0.1.2"
edition = "2024"

[dependencies]
chrono = "0.4.38"
eframe = "0.27.2"
egui = "0.27.2"
image = "0.25.1"

[build-dependencies]
winres = "0.1"

[profile.release]
lto = true
panic = 'abort'
