[package]
name = "feather_calendar"
version = "0.1.4"
edition = "2024"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
eframe = { version = "0.27.2", features = ["persistence"] }
egui = "0.27.2"
image = "0.25.1"
serde = { version = "1", features = ["derive"] }

[build-dependencies]
winres = "0.1"

[profile.release]
lto = true
panic = 'abort'
